# Generated by Django 3.2.9 on 2021-11-16 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soz', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='N_soz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_soz', models.CharField(max_length=20)),
                ('soz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.soz')),
            ],
        ),
    ]
